# Generated by Django 5.1.1 on 2024-11-23 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filemodel',
            index=models.Index(fields=['user', 'status'], name='file_manage_user_id_7b76e6_idx'),
        ),
    ]
