# Generated by Django 5.1.1 on 2024-11-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_filemodel_file_manage_user_id_7b76e6_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'permissions': [('can_add_file', 'Can add file'), ('can_view_file', 'Can view file')]},
        ),
    ]
