# Generated by Django 5.1.1 on 2024-11-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_alter_filemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'permissions': [('can_add_file', 'Can add file model'), ('can_view_file', 'Can view file model')]},
        ),
    ]
